//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessPosition.V2.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid CommentID { get; set; }
        public System.Guid PlyID { get; set; }
        public string CommentValue { get; set; }
        public bool commentEndsLine { get; set; }
    
        public virtual Ply Ply { get; set; }
    }
}
