//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessPosition.V2.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ply
    {
        public Ply()
        {
            this.Comments = new HashSet<Comment>();
            this.Variations = new HashSet<Variation>();
        }
    
        public System.Guid PlyID { get; set; }
        public Nullable<System.Guid> GameID { get; set; }
        public Nullable<System.Guid> VariationID { get; set; }
        public int PlyNumber { get; set; }
        public int SourceSquare { get; set; }
        public int DestSquare { get; set; }
        public int PromoPiece { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Game Game { get; set; }
        public virtual Variation BaseVariation { get; set; }
        public virtual ICollection<Variation> Variations { get; set; }
    }
}
