//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessPosition.V2.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Games = new HashSet<Game>();
        }
    
        public System.Guid UserID { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
    }
}
