//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessPosition.V2.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variation
    {
        public Variation()
        {
            this.Plies = new HashSet<Ply>();
        }
    
        public System.Guid VariationID { get; set; }
        public System.Guid BasePlyID { get; set; }
        public int VariationOrderID { get; set; }
    
        public virtual ICollection<Ply> Plies { get; set; }
        public virtual Ply Ply { get; set; }
    }
}
